FROM node:20

RUN npm install -g pnpm

WORKDIR /app

# Define build arguments for environment variables
ARG DATABASE_URL
ARG PORT
ARG KEYCLOAK_URL
ARG KEYCLOAK_REALM
ARG KEYCLOAK_CLIENT
ARG KEYCLOAK_CLIENT_SECRET
ARG GCS_BUCKET_NAME
ARG GCS_PROJECT_ID
ARG GCS_SA_KEY
ARG SERVICE_NAME
ARG OTEL_EXPORTER_OTLP_ENDPOINT
ARG OTEL_EXPORTER_OTLP_PROTOCOL
ARG OTEL_RESOURCE_ATTRIBUTES
ARG OTEL_LOG_LEVEL
ARG OTEL_TRACES_EXPORTER
ARG OTEL_METRICS_EXPORTER
ARG OTEL_LOGS_EXPORTER
ARG OTEL_EXPORTER_OTLP_HEADERS


# Copy package files and install dependencies
COPY ./package.json /app 
COPY ./pnpm-lock.yaml /app
RUN pnpm install

# Copy all files
COPY . /app

# Handle GCS Key: Decode Base64 to JSON file
# We assume GCS_SA_KEY is passed as a Base64 encoded string of the JSON key.
RUN echo "${GCS_SA_KEY}" | base64 -d > /app/gcs-key.json

# Set Google Application Credentials environment variable
ENV GOOGLE_APPLICATION_CREDENTIALS="/app/gcs-key.json"
ENV DATABASE_URL=${DATABASE_URL}
ENV PORT=${PORT:-3000}
ENV KEYCLOAK_REALM=${KEYCLOAK_REALM}
ENV KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT}
ENV KEYCLOAK_BASE_URL=${KEYCLOAK_URL}
ENV KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
ENV GCS_BUCKET_NAME=${GCS_BUCKET_NAME}
ENV GCS_PROJECT_ID=${GCS_PROJECT_ID}
ENV SERVICE_NAME=${SERVICE_NAME}
ENV OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
ENV OTEL_EXPORTER_OTLP_PROTOCOL=${OTEL_EXPORTER_OTLP_PROTOCOL}
ENV OTEL_RESOURCE_ATTRIBUTES=${OTEL_RESOURCE_ATTRIBUTES}
ENV OTEL_LOG_LEVEL=${OTEL_LOG_LEVEL}
ENV OTEL_TRACES_EXPORTER=${OTEL_TRACES_EXPORTER}
ENV OTEL_METRICS_EXPORTER=${OTEL_METRICS_EXPORTER}
ENV OTEL_LOGS_EXPORTER=${OTEL_LOGS_EXPORTER}
ENV OTEL_EXPORTER_OTLP_HEADERS=${OTEL_EXPORTER_OTLP_HEADERS}

# Build the application
RUN npx prisma generate
RUN npx tsc

# Start the application with OpenTelemetry instrumentation
CMD ["sh", "-c", "npx prisma migrate deploy && node --import ./dist/utils/instrumentation.js ./dist/app.js"]
EXPOSE 3000