services:
  - name: web
    dockerfile_path: Dockerfile
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME  # Required for secrets
        value: "{{ secrets.DATABASE_URL }}"  # References a DO-managed secret
    image:
        registry_type: DOCKER_HUB
        repository: ${{ secrets.DOCKER_HUB_USERNAME }}/medical-registry-api
        tag: latest
        registry_credentials: "${{ secrets.DOCKER_HUB_USERNAME }}:${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}"